### ISSUE TITLE
`book/` should not be included in the repository

### ISSUE THREAD

**Issue by klorophatu** [PandaFoss/Awesome-Arch#2]
The directory `book/` is generated by mdbook when you build the project. Is there any particular reason why it's included?

**Comment by PandaFoss** [comment]
The project's website (which appears in the description of the repository) is actually the static website provided by GitHub. Somehow the web must have access to the content inside the `book` folder. And I thought it was more pertinent to keep that folder in this repository rather than in the web site repository (where this project is imported as a submodule).

By the way, sorry for the delay in response.
